# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "39b25f1e82d4dfd85fc7a18b9e03cd0c"
name = "vishal-app"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_online_store_pages,write_files"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
